package constant

const (
	DATABASE_DRIVER   = "DATABASE_DRIVER"
	DATABASE_USER     = "DATABASE_USER"
	DATABASE_PASSWORD = "DATABASE_PASSWORD"
	DATABASE_HOST     = "DATABASE_HOST"
	DATABASE_PORT     = "DATABASE_PORT"
	DATABASE_NAME     = "DATABASE_NAME"

	APP_PORT = "APP_PORT"
)
